apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app-secret
  namespace: sample-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: example-secretstore
    kind: SecretStore
  target:
    name: sample-app-secret
  data:
    - secretKey: password
      remoteRef:
        key: sample-app-secret
        property: password
